/*
 * phase1_osal/rump_kern_globals.c — kernel globals + panic
 * expected by the imported rump kernel sources.
 *
 * Rump's own librump/rumpkern/ (which we're now compiling
 * against — see docs/rump_build_probe.md) provides real
 * implementations of mutex_init/enter/exit/cv_wait/signal/etc.
 * as thin wrappers over rumpuser_* hypercalls. But those
 * wrappers still reference a handful of kernel globals (hz,
 * panic, etc.) that classically come from the NetBSD kernel
 * proper.
 *
 * This file defines the minimum set so rump_locks.o and
 * friends can link.
 */

#include "netstack/osal.h"

#include <stdarg.h>
#include <stddef.h>

/* -------- hz — kernel clock tick rate --------
 * NetBSD kernel default is 100. Rump uses it for timedwait
 * conversions. Value doesn't have to match anything real on
 * OS4; it's just a scale factor. */
int hz = 100;

/* -------- rump-side flags --------
 * rump.h in the imported source declares these as `int`.
 * rump_threads controls whether rump spawns real threads
 * (yes for us) and lockdebug enables slow lock checking (no).
 */
int rump_threads = 1;
int rump_lockdebug = 0;

/* -------- panic — kernel abort --------
 * NetBSD's panic() is (const char *fmt, ...) and never
 * returns. Our OSAL panic does the equivalent — halts the
 * task with a DebugPrintF marker.
 */
void
panic(const char *fmt, ...)
{
    (void)fmt;
    /* TODO: format the args via a per-task static buffer +
     * vsnprintf. For now just funnel through osal_panic which
     * DebugPrintF's a short message + halts. */
    osal_panic("kernel panic (rump)");
    __builtin_unreachable();
}

/* -------- nullop / nullret — kernel stubs --------
 * Used in vtables and as default handlers throughout the
 * kernel when a subsystem doesn't want to implement a hook.
 */
int
nullop(void *arg)
{
    (void)arg;
    return 0;
}

/* -------- Memory barriers — PPC implementations --------
 * NetBSD's membar_*() family. On PPC 460 (BookE), `sync` is
 * the heavy barrier; `lwsync` is the lightweight variant used
 * by acquire/release. `eieio` orders MMIO but not RAM, so we
 * don't use it here.
 */
void membar_acquire(void)  { __asm__ __volatile__ ("lwsync" ::: "memory"); }
void membar_release(void)  { __asm__ __volatile__ ("lwsync" ::: "memory"); }
void membar_consumer(void) { __asm__ __volatile__ ("lwsync" ::: "memory"); }
void membar_enter(void)    { __asm__ __volatile__ ("sync"   ::: "memory"); }
void membar_producer(void) { __asm__ __volatile__ ("lwsync" ::: "memory"); }
void membar_sync(void)     { __asm__ __volatile__ ("sync"   ::: "memory"); }

/* -------- kpreempt hooks --------
 * Our rump kernel runs on a single AmigaOS Task at a time —
 * NetBSD-style kernel preemption doesn't apply. Return 0
 * (no preemption pending) unconditionally.
 */
int  kpreempt(int where) { (void)where; return 0; }
void kpreempt_disable(void) { }
void kpreempt_enable(void)  { }

/* -------- lockdebug — off for us --------
 * Called from inside mutex/rwlock code when LOCKDEBUG is
 * defined in the build. We build with LOCKDEBUG off (see
 * opt_rumpkernel.h), so these should never fire. Provide
 * a panic-if-called stub in case.
 */
void
lockdebug_abort(void *cookie, void *lock, const char *ops,
                const char *func, const char *msg)
{
    (void)cookie; (void)lock; (void)ops; (void)func; (void)msg;
    osal_panic("lockdebug_abort: unreachable (LOCKDEBUG disabled)");
}

/* -------- Autogenerated rump kernel bits ---------------------
 * NetBSD's build normally generates these files from templates:
 *   sys/rump/librump/rumpkern/rump_syscalls.c  (from syscalls.master)
 *   sys/rump/librump/rumpkern/rumpkern_if_wrappers.c
 * We haven't reproduced the generator. Providing weak stubs so
 * the remaining unresolved symbol count shrinks; a real port
 * will need the actual generated files (or a rewritten
 * equivalent that maps to our netstack RPCs directly). */

int  rump_nativeabi_p(void)  { return 0; }
void rump_cpu_attach(void *ci) { (void)ci; }
void rump_cpu_makeclockframe(void *cf) { (void)cf; }
void *rump_vmspace_local;
void *rump_sysent;
void *rump_sysent_nomodbits;

/* -------- VOP_* — VFS operation dispatch table ----------------
 * Autogenerated by NetBSD's build from sys/kern/vnode_if.src.
 * We're not doing filesystem — network stack builds against
 * these only for their function-pointer symbols. Stub as no-ops. */
int VOP_ADVLOCK(void *v, void *id, int op, void *fl, int flags)
{ (void)v; (void)id; (void)op; (void)fl; (void)flags; return 0; }
int VOP_GETATTR(void *v, void *vap, void *cred)
{ (void)v; (void)vap; (void)cred; return 0; }
int VOP_PATHCONF(void *v, int name, long *retval)
{ (void)v; (void)name; if (retval) *retval = 0; return 0; }
int VOP_PUTPAGES(void *v, unsigned long off, unsigned long high, int flags)
{ (void)v; (void)off; (void)high; (void)flags; return 0; }
int VOP_UNLOCK(void *v) { (void)v; return 0; }
