#!/usr/bin/env bash
# scripts/import-rump.sh — pull NetBSD rump kernel subtrees.
#
# Uses git sparse-checkout to fetch only what the network stack
# port needs. Writes the extracted source under
# vendor/netbsd-rump/{sys,common,include} and generates
# vendor/netbsd-rump/IMPORT_MANIFEST.txt so re-runs are
# reproducible (or at least auditable).
#
# On a first run this pulls ~40-80 MB of source depending on
# subtree resolution. Idempotent: re-runs update to the same ref.

set -euo pipefail

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/NetBSD/src}"
UPSTREAM_REF="${UPSTREAM_REF:-netbsd-10-1-RELEASE}"

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR_DIR="${REPO_DIR}/vendor/netbsd-rump"
WORK_DIR="${VENDOR_DIR}/.work"

# ─── Subtrees to import ───────────────────────────────────────
# Order matters only for logging. Every entry is passed to
# git sparse-checkout, then rsync'd into place.
SUBTREES=(
    "sys/rump"
    "sys/net"
    "sys/netinet"
    "sys/netinet6"
    "sys/kern"
    "sys/sys"
    "common/lib/libc/string"
    "common/lib/libc/gen"
    "include"
)

echo "=================================================================="
echo "  NetBSD rump kernel import"
echo "  Upstream: ${UPSTREAM_URL}"
echo "  Ref:      ${UPSTREAM_REF}"
echo "  Target:   ${VENDOR_DIR}"
echo "=================================================================="
echo

# ─── Clean any previous partial import ────────────────────────
for st in "${SUBTREES[@]}"; do
    if [ -d "${VENDOR_DIR}/${st}" ]; then
        echo "==> removing stale ${VENDOR_DIR}/${st}"
        rm -rf "${VENDOR_DIR}/${st}"
    fi
done
rm -rf "${WORK_DIR}"
mkdir -p "${WORK_DIR}"

# ─── Fetch minimally ──────────────────────────────────────────
echo "==> git clone (blobless, sparse) ${UPSTREAM_URL} @ ${UPSTREAM_REF}"
git clone \
    --depth 1 \
    --branch "${UPSTREAM_REF}" \
    --filter=blob:none \
    --sparse \
    "${UPSTREAM_URL}" \
    "${WORK_DIR}"

echo "==> configuring sparse-checkout with ${#SUBTREES[@]} subtrees"
( cd "${WORK_DIR}" && git sparse-checkout set --no-cone "${SUBTREES[@]}" )

# git sparse-checkout on --no-cone patterns is inclusive; the
# working tree will now materialize only those paths.
echo "==> checkout complete; materializing files"
( cd "${WORK_DIR}" && git checkout )

# ─── Move into place ──────────────────────────────────────────
mkdir -p "${VENDOR_DIR}"
for st in "${SUBTREES[@]}"; do
    src="${WORK_DIR}/${st}"
    dst="${VENDOR_DIR}/${st}"
    if [ ! -d "${src}" ]; then
        echo "!! subtree ${st} not present in checkout; skipping"
        continue
    fi
    mkdir -p "$(dirname "${dst}")"
    echo "==> installing ${st}"
    cp -R "${src}" "${dst}"
done

# ─── Manifest ─────────────────────────────────────────────────
COMMIT=$(cd "${WORK_DIR}" && git rev-parse HEAD)
DATE=$(cd "${WORK_DIR}" && git show -s --format=%cI HEAD)

{
    echo "# NetBSD rump kernel import manifest"
    echo "# Generated by scripts/import-rump.sh — do not hand-edit."
    echo
    echo "upstream_url: ${UPSTREAM_URL}"
    echo "upstream_ref: ${UPSTREAM_REF}"
    echo "upstream_sha: ${COMMIT}"
    echo "upstream_date: ${DATE}"
    echo
    echo "subtrees:"
    for st in "${SUBTREES[@]}"; do
        if [ ! -d "${VENDOR_DIR}/${st}" ]; then continue; fi
        count=$(find "${VENDOR_DIR}/${st}" -type f | wc -l | tr -d ' ')
        bytes=$(du -sk "${VENDOR_DIR}/${st}" | awk '{print $1*1024}')
        printf "  - path: %s\n    files: %s\n    bytes: %s\n" \
            "${st}" "${count}" "${bytes}"
    done
} > "${VENDOR_DIR}/IMPORT_MANIFEST.txt"

# ─── Cleanup ──────────────────────────────────────────────────
rm -rf "${WORK_DIR}"

# ─── Summary ──────────────────────────────────────────────────
TOTAL_FILES=$(find "${VENDOR_DIR}" -type f ! -name "*.md" ! -name "IMPORT_MANIFEST.txt" | wc -l | tr -d ' ')
TOTAL_KB=$(du -sk "${VENDOR_DIR}" | awk '{print $1}')

echo
echo "=================================================================="
echo "  Import complete"
echo "  Ref: ${UPSTREAM_REF} @ ${COMMIT:0:12}"
echo "  Files landed: ${TOTAL_FILES}"
echo "  Size: ${TOTAL_KB} KB"
echo "  Manifest: ${VENDOR_DIR}/IMPORT_MANIFEST.txt"
echo "=================================================================="
